<a href="https://colab.research.google.com/github/6uoas/MLwP-Cookbook/blob/main/MLwP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#creating vector
import numpy as np
vector_row = np.array([1,2,3])
vector_column = np.array([[1],
                          [2],
                          [3]])

In [2]:
vector_row, vector_column

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

In [6]:
#creating a matrix
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])

zero_matrix = np.zeros((3,2)) # input : tuple
print(zero_matrix)
one_matrix = np.ones((3,2))
print(one_matrix)

n = 10
n_matrix = np.full((3,2),n)
print(n_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]
 [10 10]]


In [8]:
#creating a sparse matrix
from scipy import sparse

matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])

matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3
