<a href="https://colab.research.google.com/github/6uoas/MLwP-Cookbook/blob/ch1-edit/MLwP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
#creating vector
import numpy as np
vector_row = np.array([1,2,3])
vector_column = np.array([[1],
                          [2],
                          [3]])

In [54]:
vector_row, vector_column

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

In [55]:
#creating a matrix
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])

zero_matrix = np.zeros((3,2)) # input : tuple
print(zero_matrix)
one_matrix = np.ones((3,2))
print(one_matrix)

n = 10
n_matrix = np.full((3,2),n)
print(n_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]
 [10 10]]


In [56]:
#creating a sparse matrix
from scipy import sparse

matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])

matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [57]:
#indexing component
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(vector[2])
print(matrix[1,1])
print(matrix[:,2])

#boolean masking
print(matrix > 5)
print(matrix[matrix>5])

3
5
[3 6 9]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


In [58]:
#describing a matrix
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

print(matrix.shape) # describing (rows, cols)
print(matrix.size) # number of components in matrix
print(matrix.ndim) # matrix-dimension

(3, 4)
12
2


In [59]:
#applying operations to elements
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

add_100 = lambda i: i+100
vectorized_add_100 = np.vectorize(add_100) # input : function
print(vectorized_add_100(matrix))# broadcasting
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
#finding the maximum and minimum values
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.max(matrix))
print(np.min(matrix))

matrix = np.array([[1,3,2],
                   [8,6,7],
                   [9,0,10]])
print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))

print()
# adjusting dimension
print(np.max(matrix, axis=1, keepdims=True))
print(np.min(matrix, axis=0, keepdims=True))

9
1
[ 3  8 10]
[1 0 2]

[[ 3]
 [ 8]
 [10]]
[[1 0 2]]


In [61]:
#calculating the average, variance, and standard deviation
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

print(np.mean(matrix, axis=1))

5.0
6.666666666666667
2.581988897471611
[2. 5. 8.]


In [62]:
#reshaping arrays
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

print(matrix.reshape(3,4))
print(matrix.reshape(2,6))
print(matrix.reshape(4,-1))
print(matrix.reshape(12))
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
#transposing a vector or matrix
matrix = np.array([[1,4,7],
                   [2,5,8],
                   [3,6,9]])
print(matrix.T)

vector = np.array([[1,2,3,4,5,6]])
print(vector.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [64]:
#flattening a matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix.flatten())
print(matrix)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
#finding the rank of a matrix
matrix = np.array([[1,1,1],
                   [1,1,10],
                   [1,1,15]])
print(np.linalg.matrix_rank(matrix))

2


> In linear algebra, the **rank** of a matrix A is the **dimension of the vector space generated (or spanned) by its columns.** *Axler, Sheldon (2015). Linear Algebra Done Right. Undergraduate Texts in Mathematics (3rd ed.).*

In [67]:
#calculating the determinant
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])
print(np.linalg.det(matrix))

0.0


In [69]:
#getting the diagonal of a matrix
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])
print(matrix.diagonal())
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=-1))

[1 4 9]
[2 6]
[2 8]


In [72]:
#calculating the trace of a matrix
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])
print(matrix.trace())
print(matrix.trace(offset=1))
print(matrix.trace(offset=-1))

14
8
10


In [74]:
#finding eigenvalues and eigenvectors
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(f"eigenvalues = {eigenvalues}")
print(f"eigenvectors = {eigenvectors}")

eigenvalues = [13.55075847  0.74003145 -3.29078992]
eigenvectors = [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [78]:
#calculating dot products
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
1*4+2*5+3*6
print(np.dot(vector_a, vector_b))

32


In [80]:
#adding and subtracting matrices
matrix_a = np.array([[1,1,1],
                     [1,1,1],
                     [1,3,8]])
matrix_b = np.array([[1,3,1],
                     [1,3,1],
                     [1,3,8]])

print(np.add(matrix_a, matrix_b))

print(np.subtract(matrix_a, matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  6 16]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0  0  0]]


In [83]:
#multplying matrices
matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                     [1,2]])
print(np.dot(matrix_a, matrix_b))
print(matrix_a @ matrix_b) # python 3.5
print()
print(matrix_a * matrix_b)

[[2 5]
 [3 7]]
[[2 5]
 [3 7]]

[[1 3]
 [1 4]]


In [85]:
#invering a matrix
matrix = np.array([[1,4],
                   [2,5]])
print(np.linalg.inv(matrix))
print(matrix @ np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [91]:
#generating random values
np.random.seed(0)
print(np.random.random(3))
print(np.random.randint(0,11,3)) # 1~10 , intiger 3EA
print(np.random.normal(0.0, 1.0, 3)) #mean, std, nEA
print(np.random.logistic(0.0, 1.0, 3)) # mean, scale, nEA
print(np.random.uniform(1.0, 2.0, 3)) # 1~2, 3EA

[0.5488135  0.71518937 0.60276338]
[3 7 9]
[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]
[1.47997717 1.3927848  1.83607876]
